### ISSUE TITLE
実行時のエラー

### ISSUE THREAD

**Issue by yncat** [actlaboratory/SOC#1]
>python soc.py
Traceback (most recent call last):
  File "soc.py", line 14, in <module>
    import app as application
  File "C:\git\SOC\app.py", line 22, in <module>
    from views import main
  File "C:\git\SOC\views\main.py", line 26, in <module>
    import Ocr
  File "C:\git\SOC\Ocr.py", line 10, in <module>
    from PIL import UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (C:\Users\nyanc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\__init__.py)

**Comment by guredora403** [comment]
仮想環境内で
pip install -r requirements.txt
を実行したらちゃんと動いたのでこのコマンドを実行しなおしたら動きませんか？

**Comment by yncat** [comment]
こっちの環境に古いバージョンのpillowが入ってたっぽい。
