### ISSUE TITLE
app.pyからviews.langDialogを呼び出すとエラーになる

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/SOC#15]
app.pyからlangDialog.showを実行するとエラーになります。
baseDialog.pyのことはよくわかりません。langDialog.pyでsuper().initializeは実行されています。
Traceback (most recent call last):
  File "soc.py", line 37, in <module>
    if __name__ == "__main__": main()
  File "soc.py", line 21, in main
    result = app.initialize()
  File "C:\python\soc\app.py", line 35, in initialize
    self.langSelecter()
  File "C:\python\soc\app.py", line 117, in langSelecter
    langSelect.Show(False)
  File "C:\python\soc\views\baseDialog.py", line 29, in Show
    self.panel.Layout()
AttributeError: 'langDialog' object has no attribute 'panel'

**Comment by guredora403** [comment]
まだpanelがないと怒られます。
