### ISSUE TITLE
アップデートのキャンセル後、やり直しができない

### ISSUE THREAD

**Issue by hrk-fujii** [actlaboratory/SOC#67]

**Comment by hrk-fujii** [comment]
まず、ダウンロードを開始したアップデートをキャンセルする。
その後、SOCを閉じずにヘルプメニューから再度アップデートを実行しようとすると、ダウンロード中の画面で停止する。
＜エラー＞
Traceback (most recent call last):
  File "\foo\soc\views\updateDialog.py", line 63, in run_update
    globalVars.update.start()
  File "threading.py", line 848, in start
RuntimeError: threads can only be started once

**Comment by guredora403** [comment]
SOCでは修正されているのでcloseします。
